[NHUB-543] Notifications issues fix (#1124)
* Prevent passing None value from `last_run_time`

`last_run_time` has been changed to be Optional and None by default in the new async resource model therefore the key `last_run_time` is always there. This change prevent from passing a None value and throwing an `AttributeError: 'NoneType' object has no attribute 'tzinfo'` exception from within `utc_to_local` function

NHUB-543

* Switch to `_created` as `created` is no longer available

`created` is no longer available in new async framework.

NHUB-543