[STTNHUB-356] fix: Unable to send empty value for UserForm (#1045)
* [STTNHUB-356] fix: Unable to send empty value for UserForm
Was causing the following exception to be raised
```
  File "newsroom/users/forms.py", line 22, in process_formdata
    self.data = [x.strip() for x in valuelist[0].split(",")]
AttributeError: 'NoneType' object has no attribute 'split'
```

* fix formatting